#-----------------------------------------------------------------------
# Site:  BareNakedCoder.com
#-----------------------------------------------------------------------
baseURL = "https://www.chess.ca/"
#languageCode = "en-us"
title = "chess.ca"
#uglyURLs = true

theme = "cfc-2020"

contentDir = "../content"
#publishDir = "../gae/static-gen"
enableRobotsTXT = true
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
enableMissingTranslationPlaceholders = false

[frontmatter]
  #---- if file is yyyy-mm-dd-post-title.md, date is from file name
  date = [":filename", ":default"]

[permalinks]
  x1news = "/news/:slug"
  x2news = "/news/:year:/:filename"
  news = "/news/:year:/:month/:day/:slug"
  cfc = "/cfc/:slug"
  clubs = "/clubs/:slug"
  players = "/players/:slug"
  tournaments = "/tournaments/:slug"
  website = "/ws/:filename"
  #blog = "/blog/:year/:month/:slug"
  #code = "/code/:slug"

[author]
  name = "CFC / FCE"

[taxonomies]
  tag = "tags"

[markup.goldmark.renderer]
  unsafe= true

[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 4
    ordered = false
